version: '3.8'

services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - '4180:4180'
    environment:
      OAUTH2_PROXY_LOGIN_URL: '${login_url}'
      OAUTH2_PROXY_REDEEM_URL: '${redeem_url}'
      OAUTH2_PROXY_VALIDATE_URL: '${validate_url}'
      OAUTH2_PROXY_COOKIE_SECRET: '${cookie_secret}'
      OAUTH2_PROXY_CLIENT_ID: '${client_id}'
      OAUTH2_PROXY_CLIENT_SECRET: '${client_secret}'
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_PROVIDER: 'github'
      OAUTH2_PROXY_UPSTREAMS: 'http://server:3030'
      OAUTH2_PROXY_REDIRECT_URL: '${redirect_url}'
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: '${provider_display_name:-GitHub}'
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: 'true'
      OAUTH2_PROXY_HTTP_ADDRESS: '0.0.0.0:4180'

  server:
    build: .
    command: ['openvscode-farm']
    environment:
      LISTEN: '0.0.0.0:3030'
      DATA_DIR: '${data_dir}'
      CONTAINER_URL: '${container_url:-http://localhost:{port}/?tkn={token}}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    security_opt:
      - label=disable
